apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Uma API RESTful construída com NestJS.
  annotations:
    github.com/project-slug: bamboo-DCM/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: dev-team
  lifecycle: experimental