services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    networks:
      - node_template
    ports:
      - "3000:3000"

  datadog:
    image: datadog/agent:latest
    # container_name: ${{values.app_name}}-datadog
    container_name: datadog
    networks:
      - node_template
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_ENV=local
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=false
      - DD_TRACE_ENABLED=true
      - DD_CONTAINER_EXCLUDE=image:redis,image:postgres,service:agent
    ports:
      - "8126:8126"
      - "8125:8125/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
networks:
    node_template: