site_name: '${{values.app_name}}'
site_description: '${{values.app_description}}'
repo_url: 'https://github.com/bamboo-DCM/${{values.app_name}}'
edit_url: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
    - Getting started: 'docs/index.md'