name: CI-CD on Develop push
on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 457992978309.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: 'bamboo-brazil-prod-${{ values.app_name }}-ecr'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:prod \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            .
