name: CI-CD on Develop push
on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ${{values.repositoryUri}}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ '${{ secrets.AWS_ACCESS_KEY_ID_PROD }}' }}
          aws-secret-access-key: ${{ '${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}' }}
          aws-region: ${{ '${{ env.AWS_REGION }}' }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REPOSITORY:prod \
            .
      
      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPOSITORY:prod
  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Deploy Coolify
        run: |
          curl -X GET "https://coolify.bamboodcm.com/api/v1/deploy?uuid=${{values.application_uuid}}&force=true" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
